### PR TITLE
Define a memmap from an indexable object + allow it to be done in parallel.

### PR DESCRIPTION
**Pull request by ahalev**
Wrote this for myself but figured I'd open a PR if you want to merge it.

Main addition is `base.from_indexable_base` which allows the construction of a memmap from an object that supports `__getitem__`. The advantage of this is that you can parallelize batch collection, which is useful if loading samples into memory is slow or you have an expensive preprocessing step.

Also supports a callable function of the form `f(i: int) -> np.ndarray`.

### CODE REVIEW

**Comment by hristo-vrigazov** [comment]
Thanks for the pull request! I'll take a closer look at it these days and we'll decide on how the public interface will look - I love the general idea, much appreciated 👏

**Comment by hristo-vrigazov** [comment]
I like it very much. Will you be able to add unit tests for `from_indexable_base` ?

**Comment by ahalev** [comment]
Added a few tests (https://github.com/hristo-vrigazov/mmap.ninja/pull/17/commits/3b05ed168bd45f9bfd4550d9bc219a310bb63b7c).

**Comment by hristo-vrigazov** [comment]
Great work, thanks! Your contribution will be added to `v0.8.0`!

**Pull request merged**
